title: Blockdia
description: An open platform for block-based programming.

remote_theme: "jekyll/minima@4de3223"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true

minima:
  skin: auto
  hide_site_feed_link: true
